import fs from 'node:fs/promises';
import {isEligible} from '../dist/core.mjs';
export function validateCatalog(data,now=new Date()){
 if(data.schema!==1||!Array.isArray(data.categories)||!Array.isArray(data.facts))throw Error('Invalid catalog');
 const cats=new Set(data.categories.map(c=>c.id)),ids=new Set(),titles=new Set(),approved=[];
 for(const f of data.facts){
  if(!/^[a-z0-9-]{1,80}$/.test(f.id)||ids.has(f.id))throw Error('Duplicate/invalid ID '+f.id);ids.add(f.id);
  if(f.workflow!=='approved')continue;
  if(!cats.has(f.category)||!f.review?.sourceChecked||!f.review?.plainLanguageChecked||!f.review?.reviewer||!f.review?.evidence||!f.review?.reviewedAt)throw Error('Missing review '+f.id);
  if(![f.title,f.shortFact,f.explanation,f.whyItMatters].every(v=>typeof v==='string'&&v.trim())||f.shortFact.length>240)throw Error('Incomplete or long card '+f.id);
  if(titles.has(f.shortFact.trim()))throw Error('Duplicate card '+f.id);titles.add(f.shortFact.trim());
  if(!isEligible(f,now))throw Error('Approved content invalid or expired: '+f.id);
  const {workflow,review,...published}=f;approved.push(published);
 }
 return approved;
}
if(process.argv[1]?.endsWith('build-content.mjs')){
 const data=JSON.parse(await fs.readFile(new URL('../content/catalog.json',import.meta.url),'utf8'));
 const published=validateCatalog(data);
 await fs.writeFile(new URL('../dist/content.mjs',import.meta.url),'// Generated from reviewed content/catalog.json. Do not edit this file.\nexport const CATEGORIES='+JSON.stringify(data.categories)+';\nexport const FACTS='+JSON.stringify(published)+';\nexport const AVAILABLE_CATEGORIES=CATEGORIES.filter(c=>FACTS.some(f=>f.category===c.id));\n');
 console.log(`Published ${published.length} approved facts; drafts/rejections excluded.`);
}
